version: "3.8"

services:

  # =============================================================
  # FRONT Test
  # =============================================================

  vitrine:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "80:80"
    volumes:
      - ./ItetsuLaTable:/app
    command: sh -c "npm install && npm run start"


  # =============================================================
  # FRONT REACT
  # =============================================================

  front:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
    command: sh -c "npm install && npm run dev"


  # =============================================================
  # API NEST
  # =============================================================

  api:
    image: node:18-alpine
    working_dir: /usr/src/app
    volumes:
      - ./nest-app:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start:dev"

  # =============================================================
  # POSTGRES
  # =============================================================

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    volumes:
      - ./postgres:/var/lib/postgresql/data

  # =============================================================
  # MONGODB
  # =============================================================

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
    volumes:
      - ./mongodb:/data/db